kind: pipeline
name: default

clone:

steps:
  - name: packager
    image: itronic/test:latest
    environment:
      FTP_USERNAME:
        from_secret: ftpusername
      FTP_PASSWORD:
        from_secret: ftppassword
      FTP_HOSTNAME: ci.joomla.org
      FTP_PORT: "21"
      FTP_DEST_DIR: /artifacts
      FTP_VERIFY: "false"
      FTP_SECURE: "true"
      HTTP_ROOT: "https://ci.joomla.org:444/artifacts"
      DRONE_PULL_REQUEST: DRONE_PULL_REQUEST
      DRONE_COMMIT: DRONE_COMMIT
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - export PULL_ID=$DRONE_PULL_REQUEST
      - echo $DRONE_COMMIT
      - export DRONE_COMMIT=$DRONE_COMMIT
      - echo $DRONE_COMMIT
      - /bin/drone_build.sh
    volumes:
      - name: reference
        path: /reference
    when:
      branch:
      - 4.0-dev
