---
kind: pipeline
name: default

clone:

steps:

  - name: composer
    image: joomlaprojects/docker-images:php7.3-composer
    depends_on: [ restore-cache ]
    commands:
      - composer validate --no-check-all --strict
      - composer install --no-progress --no-suggest

  - name: npm
    image: node:current-alpine
    depends_on: [ phpcs ]
    commands:
      - npm ci --unsafe-perm

  - name: packager
    image: itronic/test:latest
    depends_on: [ npm ]
    environment:
      FTP_USERNAME:
        from_secret: ftpusername
      FTP_PASSWORD:
        from_secret: ftppassword
      FTP_HOSTNAME: ci.joomla.org
      FTP_PORT: "21"
      FTP_DEST_DIR: /artifacts
      FTP_VERIFY: "false"
      FTP_SECURE: "true"
      BRANCH_NAME: "4.0-dev" # Current branch to check against (from repo joomla/joomla-cms)
      DRONE_PULL_REQUEST: DRONE_PULL_REQUEST
    commands:
      - export PULL_ID=$DRONE_PULL_REQUEST
      - ls -l
      - /bin/compare.sh
    volumes:
      - name: reference
        path: /reference
    when:
      branch:
      - 4.0-dev

---
kind: signature
hmac: 7649a6f9d7d15da3d8723dd7cf2d8328edc5040fb53308e10c6f07b901f87b22

...
