---
kind: pipeline
name: default

clone:

steps:
  - name: composer
    image: joomlaprojects/docker-images:php7.3
    volumes:
      - name: composer-cache
        path: /tmp/composer-cache
    commands:
      - composer validate --no-check-all --strict
      - composer install --no-progress --no-suggest
      - patch -N -p0 < tests/patch/phpunit8_php8_match.patch || echo "Ignore this error."

  - name: system-tests-mysql
    depends_on: [ composer ]
    image: joomlaprojects/docker-images:systemtests
    environment:
      JOOMLA_INSTALLATION_DISABLE_LOCALHOST_CHECK: 1
    commands:
      - bash tests/Codeception/drone-system-run.sh "$(pwd)" mysql

  - name: artifacts-system-tests
    image: cschlosser/drone-ftps
    depends_on: [ system-tests-mysql ]
    environment:
      FTP_USERNAME:
        from_secret: ftpusername
      FTP_PASSWORD:
        from_secret: ftppassword
      PLUGIN_HOSTNAME: ci.joomla.org:21
      PLUGIN_SRC_DIR: /tests/Codeception/_output/
      PLUGIN_DEST_DIR: /artifacts
      PLUGIN_SECURE: false
      PLUGIN_EXCLUDE: ^\.git/$
    commands:
      - export PLUGIN_DEST_DIR=$PLUGIN_DEST_DIR/$DRONE_REPO/$DRONE_BRANCH/$DRONE_PULL_REQUEST/system-tests/$DRONE_BUILD_NUMBER
      - echo https://ci.joomla.org$PLUGIN_DEST_DIR
      - /bin/upload.sh
    when:
      status:
        - failure

branches:
  exclude: [ l10n_* ]

volumes:
- name: composer-cache
  host:
    path: /tmp/composer-cache

services:
  - name: mysql
    image: mysql:5.7
    environment:
      MYSQL_USER: joomla_ut
      MYSQL_PASSWORD: joomla_ut
      MYSQL_ROOT_PASSWORD: joomla_ut
      MYSQL_DATABASE: test_joomla

---
kind: signature
hmac: f99784b6fd6bf3707a600f262bb9e59aa7b5f97e54df8976e459096de4344ef3

...
