---
kind: pipeline
name: default

clone:

steps:
  - name: composer
    image: joomlaprojects/docker-images:php7.3
    volumes:
      - name: composer-cache
        path: /tmp/composer-cache
    commands:
      - composer validate --no-check-all --strict
      - composer install --no-progress --no-suggest
      - patch -N -p0 < tests/patch/phpunit8_php8_match.patch || echo "Ignore this error."

  - name: npm
    image: node:14-alpine
    depends_on: [ composer ]
    commands:
      - npm ci --unsafe-perm

  - name: system-tests-mysql
    depends_on: [ composer ]
    image: joomlaprojects/docker-images:systemtests
    environment:
      JOOMLA_INSTALLATION_DISABLE_LOCALHOST_CHECK: 1
      APACHE_LOG_DIR: /tests/Codeception/_output
    commands:
#      - sed -i 's/#LogLevel info/LogLevel debug/g' /etc/apache2/sites-available/000-default.conf
      - mv apache.conf /etc/apache2/sites-available/000-default.conf
      - cat /etc/apache2/sites-available/000-default.conf
      #- echo "error_log $(pwd)/tests/Codeception/_output/php_erros.log" >> /etc/php/7.2/apache2/php.ini
      - echo "error_log /tests/www/php_errors.loh" >> /etc/php/7.2/apache2/php.ini
      - tail /etc/php/7.2/apache2/php.ini
      - bash tests/Codeception/drone-system-run.sh "$(pwd)" mysql

  - name: system-tests-mysql8
    depends_on: [ system-tests-mysql ]
    image: joomlaprojects/docker-images:systemtests
    environment:
      JOOMLA_INSTALLATION_DISABLE_LOCALHOST_CHECK: 1
    commands:
      - bash tests/Codeception/drone-system-run.sh "$(pwd)" mysql8

  - name: system-tests-postgres
    depends_on: [ system-tests-mysql8 ]
    image: joomlaprojects/docker-images:systemtests
    environment:
      JOOMLA_INSTALLATION_DISABLE_LOCALHOST_CHECK: 1
    commands:
      - bash tests/Codeception/drone-system-run.sh "$(pwd)" postgres

  - name: api-tests
    depends_on: [ system-tests-postgres ]
    image: joomlaprojects/docker-images:systemtests
    environment:
      JOOMLA_INSTALLATION_DISABLE_LOCALHOST_CHECK: 1
    commands:
      - bash tests/Codeception/drone-api-run.sh "$(pwd)"

  - name: artifacts-system-tests
    image: cschlosser/drone-ftps
    depends_on: [ api-tests ]
    environment:
      FTP_USERNAME:
        from_secret: ftpusername
      FTP_PASSWORD:
        from_secret: ftppassword
      PLUGIN_HOSTNAME: ci.joomla.org:21
      PLUGIN_SRC_DIR: /tests/Codeception/_output/
      PLUGIN_DEST_DIR: /artifacts
      PLUGIN_SECURE: false
      PLUGIN_EXCLUDE: ^\.git/$
    commands:
      - export PLUGIN_DEST_DIR=$PLUGIN_DEST_DIR/$DRONE_REPO/$DRONE_BRANCH/$DRONE_PULL_REQUEST/system-tests/$DRONE_BUILD_NUMBER
      - echo https://ci.joomla.org$PLUGIN_DEST_DIR
      - /bin/upload.sh
    when:
      status:
        - failure

branches:
  exclude: [ l10n_* ]

volumes:
- name: composer-cache
  host:
    path: /tmp/composer-cache

services:
  - name: mysql
    image: mysql:5.7
    environment:
      MYSQL_USER: joomla_ut
      MYSQL_PASSWORD: joomla_ut
      MYSQL_ROOT_PASSWORD: joomla_ut
      MYSQL_DATABASE: test_joomla

  - name: mysql8
    image: mysql:8
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_USER: joomla_ut
      MYSQL_PASSWORD: joomla_ut
      MYSQL_ROOT_PASSWORD: joomla_ut
      MYSQL_DATABASE: test_joomla

  - name: postgres
    image: postgres:11-alpine
    ports:
      - 5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: joomla_ut
      POSTGRES_DB: test_joomla

---
kind: signature
hmac: eeef976e7f7c7dde8100d7dc4944250af4886b397250aab5c8069a021f4e3043

...
